[project]
name = "First-Site"
version = "0.1"
description = "A sample Python project"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  {name = "Brian Kanyora", email = "briankanyora@gmail.com" }
]

classifiers = [  
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

dependencies = [
    "blinker==1.7.0"
    "click==8.1.7"
    "colorama==0.4.6"
    "Flask==3.0.0"
    "itsdangerous==2.1.2"
    "Jinja2==3.1.2"
    "MarkupSafe==2.1.3"
    "Werkzeug==3.0.1"
]

[project.urls] 
"Homepage" = "https://github.com/briankanyora/First-Site"
"Bug Reports" = "https://github.com/briankanyora/First-Site/issues"

[project.scripts]
first_site = "first_site:main"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true
license-files = ["LICENSE"]

[tool.isort]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"

[tool.black]
line-length = 120

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"